name: Onkyo by RK
version: 0.1.7
slug: onkyo_by_rk
description: Onkyo/Pioneer eISCP integration
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: false
options:
  host: ""
  port: 60128
schema:
  host: str
  port: port
