name: Demo Addon by RK
version: 0.1.7
slug: demo_addon_by_rk
description: Demo addon for testing
arch:
  - amd64
  - aarch64
startup: application
boot: manual
ingress: false
options:
  message: "Hello World"
schema:
  message: str
