name: Tuya Local by RK
version: 0.1.7
slug: tuya_local_by_rk
description: Local Tuya integration
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: false
options:
  devices: []
schema:
  devices:
    - str
